{% set name = "mri" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mri-{{ version }}.tar.gz
  sha256: a3778ac2d7e8f22e9499e46c590408ae3236f9703b7782840d451832c7e9ccef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - mri = mri.commands.main:run

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=64.0.0
  run:
    - numpy >=1.21
    - packaging
    - psutil
    - python >=3.9

test:
  imports:
    - mri
  commands:
    - pip check
    - mri-sys_info
  requires:
    - pip

about:
  home: https://scott-huberty.github.io/mri-python/dev/index.html
  summary: MRI-Python is a Python package for working with MRI data.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/scott-huberty/mri-python

extra:
  recipe-maintainers:
    - scott-huberty
